### ISSUE TITLE
Add optional features

### ISSUE THREAD

**Issue by sa9St** [TehGM/Wolfringo#1]
please add these features if possible 
-Device type control
-Login as (Online,busy,away..etc)

**Comment by TehGM** [comment]
Login as unfortunatelly isn't supported by Wolf protocol by the looks of it. Instead, library allows you to set online state right after you log in - either by using Sender's SetOnlineStateAsync method, or sending a OnlineStateUpdateMessage.

Device type control is already implemented - one of WolfClient constructor overloads takes a device string.  
In db4089d, I changed that string to WolfDevice enum. Additionally, added overload for ConnectAsync method that allows setting the device for the new connection - note that this overload is only available in WolfClient class, and isn't a part of IWolfClient interface.  
Unfortunately, it seems Wolf protocol does not allow changing the device type once connection is established, so it has to be done via constructor/on connection, and cannot be done during login.

This change is a part of v0.3.3 release, which is now available to download.
