### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by sa9St** [TehGM/Wolfringo#2]
After a while the bot reconnect even when it's connected i tried to catch all exception but it didn't work so i created my own reconnector. if this a personal problem please guide me to solve it. 

```
 ---> System.InvalidOperationException: Already connected
   at TehGM.Wolfringo.WolfClient.ConnectAsync(CancellationToken cancellationToken)
   at TehGM.Wolfringo.Utilities.WolfClientReconnector.OnClientDisconnected(Object sender, EventArgs e)
   --- End of inner exception stack trace ---
```

**Comment by TehGM** [comment]
Hi @sa9St.
I assume you're using version v0.3.2 of the library?
What more or less your reconnection code looks like?

**Comment by sa9St** [comment]
Yes i am using 0.3.2, it is a simple code i wrote and still sometimes throws unhandled exception


```
            _client.Disconnected += _client_Disconnected;
            _client.Connected += _client_Connected;


        private static async void _client_Connected(object sender, EventArgs e)
        {
            isconnected = true;
        }
        private static async void _client_Disconnected(object sender, EventArgs e)
        {
            if (isconnected != true)
            await _client.ConnectAsync();
        }
```

**Comment by TehGM** [comment]
Okay. I'll see if I can replicate the issue and work on a fix.

**Comment by sa9St** [comment]
> What more or less your reconnection code looks like? I see you're using reconnector utility when this exception happens - how are you initializing it?

```
            WolfClientReconnector reconnector = new WolfClientReconnector(_client);
            reconnector.FailedToReconnect += OnFailedToReconnect;
```

> Also - I assume you're not using .NET Core Host with Wolfringo.Hosting package - HostedWolfClient has reconnection built-in, so WolfClientReconnector wouldn't work with it.

Yes i am not using the Hosting package

**Comment by TehGM** [comment]
I did a few changes to combat this bug: 6cfbc66 and 909257c. According to my tests I ran briefly today, it solves issues with WolfClientReconnector. This change is a part of version 0.3.3.

Of course this type of issues are hard to debug and verify, as they're fairly conditional, so if version 0.3.3 does not fix this, feel free to re-open this issue!
