### ISSUE TITLE
Task canceled exception

### ISSUE THREAD

**Issue by sa9St** [TehGM/Wolfringo#3]
This exception will happen after the bot disconnect and reconnect again, it will cancel all the tasks after the re connection. you can work around it by adding a checker if the task was canceled and reassign it again but the bot wont listen to any other commands.

```
System.Threading.Tasks.TaskCanceledException
  Message=A task was canceled.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TehGM.Wolfringo.WolfClient.<SendAsync>d__72`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by TehGM** [comment]
Hi, The connection tasks are indeed canceled after disconnection (but before Disconnected event is raised). They are also canceled and token is recreated just before Connected event is raised. This behaviour is intended, as no connection tasks can really be executed until the client reconnects.

I am not entirely sure what exactly you're trying to - could you please advise? What do you mean b saying that bot won't listen to any other commands?

**Comment by sa9St** [comment]
After the bot disconnect and reconnect automatically. all tasks are canceled and the bot never listen to commands such as (&display Chess scores) for example.

**Comment by TehGM** [comment]
Yes, I was just able to replicate the issue. I'll investigate it.

**Comment by TehGM** [comment]
@sa9St Upon investigation, I found why the bot no longer receives messages - it's actually a mistake in my example on how to handle a welcome message when not using Hosting package. Following workaround should solve the issue:
```csharp
private static async void OnWelcome(WelcomeEvent message)
{
    if (message.LoggedInUser == null)
    {
        await _client.LoginAsync(/* username and password */);
    }
    else
    {
        await _client.SendAsync(new SubscribeToPmMessage());
        await _client.SendAsync(new SubscribeToGroupMessage());
    }
}
```
The reason why it didn't work after reconnection is cause LoginAsync actually sends these 2 messages internally - and after reconnection, user is automatically logged in, so LoginAsync is not called in my original example. I'll update example, and later see about having some helper method like "SubscribeAllAsync" to make this simpler.


Visual Studio still reports exception, but in my tests it appears it's not breaking anything and doesn't even appear in logs. I'll see if there's something simple I can do to prevent it, but it's likely just internal cancellation handling - do let me know if it breaks the bot for you, but I think everything will be fine.

**Comment by TehGM** [comment]
Documentation updated in f9f2226.

**Comment by sa9St** [comment]
i believe your right i didn't even see this code or even debug it ,now it make more sense. i will test it and replay back. thanks.

**Comment by sa9St** [comment]
Hi, After the reconnection this error will show up even if was surrounded by try and catch it will stop completely from responding to users commands. 

```
TehGM.Wolfringo.MessageSendingException
  HResult=0x80131500
  Message=Server responded with non-success status code: 500 (InternalServerError)
  Source=Wolfringo.Core
  StackTrace:
   at TehGM.Wolfringo.WolfClient.<SendAsync>d__72`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NewWolfApp.Program.<OnWelcome>d__5.MoveNext()

```

**Comment by TehGM** [comment]
Hi. This error is different - it means that WOLF servers had error when processing a message. Knowing WOLF servers, it's unfortunately bound to happen sometimes.
My suggestion is to try it again at different time.

**Comment by sa9St** [comment]
Problem is solved. i will close this issue. thank you

**Comment by TehGM** [comment]
Yes - when message.LoggedInUser is null, you need to use _client.LoginAsync - but I assume you simply removed that line to hide credentials, in which case it's okay. In afef693 I made so the else part will not be needed - this will be a part of a future version. For now (until version after 0.3.3 is released), this workaround is the correct way.

I am not able to replicate this. Does this error happen every time after reconnection, or did it happen once? If just once, I am willing to bet it was one of these times where WOLF server broke.

**Comment by sa9St** [comment]
> Yes - when message.LoggedInUser is null, you need to use _client.LoginAsync - but I assume you simply removed that line to hide credentials, in which case it's okay. In [afef693](https://github.com/TehGM/Wolfringo/commit/afef693a95a4b20f97e9f9085c8454b9bc11d329) I made so the else part will not be needed - this will be a part of a future version. For now (until version after 0.3.3 is released), this workaround is the correct way.
> 
> I am not able to replicate this. Does this error happen every time after reconnection, or did it happen once? If just once, I am willing to bet it was one of these times where WOLF server broke.

hey , yes i removed the function to hide my credentials. 
the bot was running for 8 hours it happened : 4 times in total of the 8 hours.
during that time no errors happened and it's running smoothly even tho i am putting a heavy test on it. thank you for your clarification.

**Comment by sa9St** [comment]
this problem is solved.
