### ISSUE TITLE
Not Connected

### ISSUE THREAD

**Issue by KevinAnass** [TehGM/Wolfringo#6]
When I try to login with email or google throw an exception and message with not connected

**Comment by TehGM** [comment]
Hi @KevinAnass,
I could do with more details. How exactly are you trying to login? What does the exception say?

**Comment by KevinAnass** [comment]
I just try to login with my google account and the result is not connected

**Comment by TehGM** [comment]
This appears to be a documentation error - my bad.
I updated the example in README in 5f668c15374da1aca709ebb74ac659ce2b243850.

Basically, you need to call ConnectAsync() before trying to login. Logging in should be in client's Welcome event.
Please let me know if it sorts out the problem for you!

**Comment by KevinAnass** [comment]
thank you bro
